name: mbungeweb
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  agora:
    git: https://github.com/Iampato/AgoraWebPlugin.git
  animations: ^1.1.2
  bloc: ^6.1.1
  charts_flutter: ^0.9.0
  cupertino_icons: ^1.0.2
  equatable: ^1.2.5
  file_picker: ^2.1.5+1
  flutter_bloc: ^6.1.1
  flutter_spinkit: ^4.1.2+1
  fluttertoast: ^7.1.6
  google_maps_flutter: ^0.5.28
  google_maps_flutter_web: ^0.1.0
  http: ^0.12.2
  intl: ^0.16.1
  logger: ^0.9.4
  pdf: ^2.1.0
  responsive_framework: ^0.0.14
  shared_preferences: ^0.5.12+4
  statsfl: ^1.1.0+3
  web_socket_channel: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
